apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 783256414257.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 783256414257.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: d7e17c7a
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
